watch_epics.py was not able to run myStats or myget to inspect the EPICS PVs.




This message was generated by Naomi's watch_epics script, running as a cron job on gluon153.

